import { Button, HorizontalBox, VerticalBox, AboutSlint } from "std-widgets.slint";

export component AppWindow inherits Window {
    in-out property<int> counter: 42;
    callback request-increase-value();
    VerticalBox {
        AboutSlint {  }
        Text {
            horizontal-alignment: center;
            text: "Counter: \{root.counter}";
        }
        HorizontalBox {
            alignment: center;
            Button {
                text: "Increase value";
                clicked => {
                    root.request-increase-value();
                }
            }
        }
     }
}
