FROM torizonextras/torizoncore-dev-tasks

# we need curl for TCB
RUN apt-get update && \
    apt-get install -y \
    curl \
    git \
    && \
    apt-get clean && apt-get autoremove && \
    rm -rf /var/lib/apt/lists/*

# use docker tools
COPY --from=docker:dind /usr/local/bin/docker /usr/local/bin/
COPY --from=docker:dind /usr/libexec/docker/cli-plugins /usr/local/lib/docker/cli-plugins

# the workspace will be the mount point for local path
WORKDIR /workspace

ENTRYPOINT []

CMD [ "pwsh" ]
