ARG BRANCH=dev
ARG REPO=commontorizon/vscode-torizon-templates

FROM commontorizon/pwsh:${BRANCH}

ARG BRANCH
ARG REPO

RUN apt-get update && \
    apt-get install -y \
    curl \
    wget \
    git \
    && \
    apt-get clean && apt-get autoremove && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /root
RUN git clone --branch ${BRANCH} \
    https://github.com/${REPO}.git

WORKDIR /workspace

ENTRYPOINT [ "pwsh", "-c" ]

CMD [ "/scripts/tasks.ps1" ]
