version: "3.9"
services:
  tasks:
    build:
      context: ../
      dockerfile: container/Containerfile.tasks
    image: torizonextras/torizoncore-dev-tasks:${BRANCH}

  pwsh-gitlab:
    build:
      context: ../
      dockerfile: container/Containerfile.gitlab
      args:
        - BRANCH=${BRANCH}
    image: torizonextras/pwsh-gitlab:${BRANCH}
