version: "3.9"
services:
  pwsh:
    build:
      context: ../
      dockerfile: container/Containerfile.pwsh
    image: commontorizon/pwsh:${BRANCH}

  tasks:
    build:
      context: ../
      dockerfile: container/Containerfile.tasks
      args:
        - BRANCH=${BRANCH}
        - REPO=toradex/vscode-torizon-templates
    image: commontorizon/torizon-dev-tasks:${BRANCH}

  pwsh-gitlab:
    build:
      context: ../
      dockerfile: container/Containerfile.gitlab
      args:
        - BRANCH=${BRANCH}
    image: commontorizon/pwsh-gitlab:${BRANCH}

  torizon-dev:
    build:
      context: ../
      dockerfile: container/Containerfile.dev
      args:
        - BRANCH=${BRANCH}
        - UID=${UUID}
    image: commontorizon/torizon-dev:${BRANCH}
    privileged: true
    network_mode: host
    environment:
      - APOLLOX_TEMPLATES_GIT_REPO=https://github.com/toradex/vscode-torizon-templates.git
      - APOLLOX_TEMPLATES_GIT_REPO_BRANCH=${BRANCH}
      #- APOLLOX_TEMPLATES_GIT_TAG=
      - WSL_DISTRO_NAME=${WSL_DISTRO_NAME}
      - APOLLOX_CONTAINER=1
      - UUID=${UUID}
      - DGID=${DGID}
      - UUSER=${USER}
      - APOLLOX_WORKSPACE=${PWD}
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /run/user/${UUID}:/run/user/${UUID}
      - /mnt:/mnt
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/run/dbus:/var/run/dbus
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
      - ${HOME}/.tcd/:/root/.tcd/
      - ${PWD}:/workspace
      - ${PWD}:${PWD}
    container_name: torizon-dev-${SHA_DIR}
    stdin_open: true
    tty: true
    pid: host
